#!/usr/bin/env python3
import os
import sys
import struct
import zlib

def strip_png(data):
    """Strip ancillary metadata chunks from PNGs, keeping only critical chunks."""
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        return data
    out = b"\x89PNG\r\n\x1a\n"
    pos = 8
    while pos < len(data):
        if pos + 12 > len(data):
            break
        length = struct.unpack(">I", data[pos:pos+4])[0]
        chunk_type = data[pos+4:pos+8]
        chunk = data[pos:pos+12+length]
        pos += 12 + length
        # Keep critical image chunks + transparency
        if chunk_type in [b"IHDR", b"PLTE", b"IDAT", b"IEND", b"tRNS"]:
            out += chunk
    return out

def parent_dir_name(file_path):
    return os.path.basename(os.path.dirname(file_path))

def registry_key(file_path, stem):
    """Runtime lookup name. ui_win/win_foo.png stays 'foo' so existing C++ names work."""
    parent = parent_dir_name(file_path)
    if parent == "ui_win" and stem.startswith("win_"):
        return stem[4:]
    return stem

def main():
    repo_root = os.path.dirname(os.path.abspath(__file__))
    icons_dir = os.path.join(repo_root, "icons")
    start_icons_dir = os.path.join(icons_dir, "start")
    sidebar_patterns_dir = os.path.join(icons_dir, "sidebar_patterns")
    sidebar_pictures_dir = os.path.join(icons_dir, "sidebar_pictures")
    top_pix_dir = os.path.join(icons_dir, "top_pix")
    ui_win_dir = os.path.join(icons_dir, "ui_win")
    ui_kde_dir = os.path.join(icons_dir, "ui_kde")
    ui_alt_dir = os.path.join(icons_dir, "ui_alt")
    ui_alt2_dir = os.path.join(icons_dir, "ui_alt2")
    users_pix_dir = os.path.join(icons_dir, "users_pix")
    
    root_start_dir = os.path.join(repo_root, "start")
    root_sidebar_patterns_dir = os.path.join(repo_root, "sidebar_patterns")
    root_sidebar_pictures_dir = os.path.join(repo_root, "sidebar_pictures")
    root_top_pix_dir = os.path.join(repo_root, "top_pix")
    root_users_pix_dir = os.path.join(repo_root, "users_pix")
    
    search_dirs = [
        icons_dir, start_icons_dir, sidebar_patterns_dir, sidebar_pictures_dir, top_pix_dir,
        ui_win_dir, ui_kde_dir, ui_alt_dir, ui_alt2_dir, users_pix_dir,
        root_start_dir, root_sidebar_patterns_dir, root_sidebar_pictures_dir, root_top_pix_dir, root_users_pix_dir
    ]
    
    image_files = []
    seen_entries = set()
    
    for d in search_dirs:
        if not os.path.isdir(d):
            continue
        for f in sorted(os.listdir(d)):
            if f.endswith(".png") or f.endswith(".svg") or f.endswith(".svgz"):
                full_path = os.path.join(d, f)
                parent_dir = os.path.basename(d)
                stem = os.path.splitext(f)[0]
                entry_key = (parent_dir, stem)
                if entry_key not in seen_entries:
                    seen_entries.add(entry_key)
                    image_files.append(full_path)
    
    if not image_files:
        print("No icon files found!")
        sys.exit(1)
        
    out_header_path = os.path.join(repo_root, "src", "applet", "classicx_embedded_icons.h")
    
    names_blob = bytearray()
    raw_data_blob = bytearray()
    entries = []
    
    for file_path in image_files:
        basename = os.path.basename(file_path)
        stem = os.path.splitext(basename)[0]
        key_name = registry_key(file_path, stem)
        if "search_empty" in key_name:
            key_name = "search_empty"
            
        with open(file_path, 'rb') as f:
            file_data = f.read()
            
        if file_path.endswith(".png"):
            file_data = strip_png(file_data)
            
        name_offset = len(names_blob)
        name_bytes = key_name.encode('utf-8') + b'\0'
        names_blob.extend(name_bytes)
        
        data_offset = len(raw_data_blob)
        data_size = len(file_data)
        raw_data_blob.extend(file_data)
        
        parent_dir = parent_dir_name(file_path)
        is_start = 1 if parent_dir == "start" else 0
        is_pattern = 2 if parent_dir == "sidebar_patterns" else 0
        is_picture = 4 if parent_dir == "sidebar_pictures" else 0
        is_top_pix = 8 if parent_dir == "top_pix" else 0
        is_user_pix = 16 if parent_dir == "users_pix" else 0
        flags = is_start | is_pattern | is_picture | is_top_pix | is_user_pix
        
        entries.append((name_offset, data_offset, data_size, flags))
        
    uncompressed_size = len(raw_data_blob)
    compressed_data_blob = zlib.compress(raw_data_blob, 9)
    compressed_size = len(compressed_data_blob)
    
    header = []
    header.append("/* Auto-generated by convert_images.py - DO NOT EDIT MANUALLY */")
    header.append("#ifndef CLASSICX_EMBEDDED_ICONS_H")
    header.append("#define CLASSICX_EMBEDDED_ICONS_H\n")
    header.append("#include <stddef.h>")
    header.append("#include <stdint.h>\n")
    
    header.append("const unsigned char* getUncompressedEmbeddedIconsData();\n")
    
    # Names blob
    header.append(f"static const char classicx_embedded_icons_names[{len(names_blob)}] = {{")
    for i in range(0, len(names_blob), 16):
        chunk = names_blob[i:i+16]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(names_blob) else ""
        header.append(f"    {hex_str}{comma}")
    header.append("};\n")
    
    # Compressed Data blob
    header.append(f"static const size_t classicx_embedded_icons_uncompressed_size = {uncompressed_size};")
    header.append(f"static const size_t classicx_embedded_icons_compressed_size = {compressed_size};\n")
    header.append(f"static const unsigned char classicx_embedded_icons_compressed_data[{compressed_size}] = {{")
    for i in range(0, len(compressed_data_blob), 16):
        chunk = compressed_data_blob[i:i+16]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(compressed_data_blob) else ""
        header.append(f"    {hex_str}{comma}")
    header.append("};\n")
    
    # Entry struct
    header.append("""struct ClassicXEmbeddedIconEntry {
    uint16_t name_offset;
    uint32_t data_offset;
    uint32_t size;
    uint8_t  flags;

    const char* name() const {
        return &classicx_embedded_icons_names[name_offset];
    }
    const unsigned char* data() const {
        const unsigned char* base = getUncompressedEmbeddedIconsData();
        return base ? &base[data_offset] : 0;
    }
    bool is_start_icon() const { return (flags & 1) != 0; }
    bool is_sidebar_pattern() const { return (flags & 2) != 0; }
    bool is_sidebar_picture() const { return (flags & 4) != 0; }
    bool is_top_pix() const { return (flags & 8) != 0; }
    bool is_user_pix() const { return (flags & 16) != 0; }
};
""")
    
    # Registry table
    header.append(f"static const ClassicXEmbeddedIconEntry classicx_embedded_icons_registry[{len(entries)}] = {{")
    for name_offset, data_offset, data_size, flags in entries:
        header.append(f"    {{ {name_offset}, {data_offset}, {data_size}, {flags} }},")
    header.append("};\n")
    header.append(f"static const size_t classicx_embedded_icons_count = {len(entries)};\n")
    header.append("#endif // CLASSICX_EMBEDDED_ICONS_H\n")
    
    with open(out_header_path, "w", encoding="utf-8") as f:
        f.write("\n".join(header))
        
    print(f"Generated {out_header_path} with {len(entries)} embedded icons (Compressed: {compressed_size} bytes, Uncompressed: {uncompressed_size} bytes, Ratio: {compressed_size/uncompressed_size*100:.1f}%, Names: {len(names_blob)} bytes).")

if __name__ == "__main__":
    main()
